server.port=3001

spring.data.mongodb.uri=${MONGO_URI:mongodb://127.0.0.1:27017/superData}

app.environment=${NODE_ENV:development}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always